version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
